channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=23.0.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.3.3
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env